Models/BankNoteViewModel.cs
namespace cashMachine.Models;

public class BankNoteViewModel
{
 public BankNoteViewModel() {}

 public int Worth { get; set; }
 public int Qtt { get; set; }

  public BankNoteViewModel(int worth, int qtt)
  {
    this.Worth = worth;
    this.Qtt = qtt;
  }

}

Models/CashMachineViewModel.cs
using System.ComponentModel.DataAnnotations;
namespace cashMachine.Models;

public class CashMachineViewModel
{

  [Display(Name = "Valor de saque: R$")]
  public int Num { get; set; }

  [Display(Name = "Quantidade de notas")]
  [DataType(DataType.MultilineText)]
  public List<BankNoteViewModel>? Result { get; set; }

}

Models/ErrorViewModel.cs
namespace cashMachine.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/IndexViewModel.cs
namespace cashMachine.Models;

public class IndexViewModel
{
  public CashMachineViewModel? CashMachine { get; set; }
  public BankNoteViewModel? BankNote { get; set; }
}

Controllers/CashMachineController.cs
using Microsoft.AspNetCore.Mvc;
using cashMachine.Models;

namespace cashMachine.Controllers;

public class CashMachineController: Controller
{
  [HttpGet]
    public ActionResult Index()
    {
      return View();
    }

    static List<BankNoteViewModel>? bankNotes;

    [HttpPost]
    public ActionResult Index(IndexViewModel indexViewModel)
    {
      ModelState.Clear();
      if (indexViewModel.CashMachine != null)
      {
        bankNotes = new List<BankNoteViewModel>();

        bankNotes.Add(new BankNoteViewModel(200, 0));
        bankNotes.Add(new BankNoteViewModel(100, 0));
        bankNotes.Add(new BankNoteViewModel(50, 0));
        bankNotes.Add(new BankNoteViewModel(20, 0));
        bankNotes.Add(new BankNoteViewModel(10, 0));
        bankNotes.Add(new BankNoteViewModel(5, 0));
        bankNotes.Add(new BankNoteViewModel(2, 0));

          while ((indexViewModel.CashMachine.Num % 5) != 0) {
            indexViewModel.CashMachine.Num -= 2;
            bankNotes[6].Qtt += 1;
          }

          bankNotes.ForEach(delegate(BankNoteViewModel b)
          {
            if ( indexViewModel.CashMachine.Num > 0 ) {
              b.Qtt = indexViewModel.CashMachine.Num / b.Worth;
              indexViewModel.CashMachine.Num -= b.Qtt * b.Worth;
            }
          });

          indexViewModel.CashMachine.Result = bankNotes;
      }

      return View(indexViewModel);
    }
}

Views/CashMachine/index.cshtml
@model cashMachine.Models.IndexViewModel

@{
    ViewData["Title"] = "Máquina de saque";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    try
    {
        <div class="form-horizontal">
            <h4>@ViewBag.Title</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CashMachine.Num, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CashMachine.Num, new { htmlAttributes = new { @class = "form-control"} })
                    @Html.ValidationMessageFor(model => model.CashMachine.Num, "", new { @clas = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CashMachine.Result, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">

                    <ul style="list-style-type: none">
                        @foreach (var item in Model.CashMachine.Result)
                        {
                            if (item.Qtt == 1) {
                                <li>@item.Qtt nota no valor de R$ @item.Worth</li>
                            }
                            if (item.Qtt > 1) {
                                <li>@item.Qtt notas no valor de R$ @item.Worth</li>
                            }
                        }
                    </ul>
                    
                </div>
            </div>
        </div>
    }
    catch (NullReferenceException e)
    {
        Console.WriteLine(e.Message);
    }

    <button type="submit" class="btn btn-primary">
        Calcular
    </button>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/cashMachine.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="CashMachine" asp-action="Index">Cash Machine</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - cashMachine 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>